keySet = {
    'str' ...
    'bigger_than_magnitude' ...
    'location_label' ...
    'max_epochs'
};
valueSet = {
    "str" ...
    5 ...
    6 ...
    1
};
optMap = containers.Map(keySet,valueSet);

seq2seqFunc(optMap);